name: Test-Crosscompile
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Test-Crosscompile:
    runs-on: "ubuntu-24.04"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "gowridurgad/setup-go@testing-cache"
      with:
        go-version: "1.24.0"
    - name: "provision go tools"
      run: "make go"
    - run: "mage port"
  
